// ============================================================
// models/Alert.js - System Alerts Schema
// ============================================================

const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema({
  type: {
    type: String,
    required: true,
    enum: ['bed_shortage', 'equipment_shortage', 'staff_shortage', 'high_patient_inflow', 'maintenance_due', 'critical_patient', 'system']
  },
  severity: {
    type: String,
    enum: ['critical', 'high', 'medium', 'low', 'info'],
    default: 'medium'
  },
  title: {
    type: String,
    required: true
  },
  message: {
    type: String,
    required: true
  },
  department: String,
  resourceId: mongoose.Schema.Types.ObjectId,
  resourceType: {
    type: String,
    enum: ['Bed', 'Equipment', 'Staff', 'Patient']
  },
  isRead: {
    type: Boolean,
    default: false
  },
  isResolved: {
    type: Boolean,
    default: false
  },
  resolvedAt: Date,
  resolvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  autoGenerated: {
    type: Boolean,
    default: true
  },
  metadata: mongoose.Schema.Types.Mixed
}, {
  timestamps: true
});

alertSchema.index({ isRead: 1, isResolved: 1, createdAt: -1 });

module.exports = mongoose.model('Alert', alertSchema);
